services:
  postgres:
    image: ankane/pgvector
    container_name: andino-web-postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data_andino:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=andino

volumes:
  postgres_data_andino:
