service: nextjs-lambda

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    NODE_ENV: production
    MAIL_RECEIVER_URL: ${env:MAIL_RECEIVER_URL}

functions:
  emailProxy:
    handler: lambda/emailProxy.handler
    events:
      - httpApi:
          path: /email-proxy
          method: POST

package:
  exclude:
    - node_modules/**
    - .git/**
  include:
    - lambda/**

plugins:
  - serverless-plugin-typescript
